# Generated by Django 3.2.6 on 2023-11-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_release_date', models.DateField()),
                ('job_closing_date', models.DateField()),
                ('job_location', models.CharField(max_length=255)),
                ('about_company', models.TextField()),
                ('project_role', models.CharField(max_length=255)),
                ('project_role_desc', models.TextField()),
                ('work_experience', models.PositiveIntegerField()),
                ('must_have_skills', models.TextField()),
                ('good_to_have_skills', models.TextField()),
                ('job_requirements', models.TextField()),
                ('qualifications', models.TextField()),
                ('job_type', models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime'), ('Internship', 'Internship')], max_length=100)),
            ],
        ),
    ]
