# Generated by Django 3.2.6 on 2023-11-15 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('username', models.CharField(editable=False, max_length=100)),
                ('email', models.EmailField(editable=False, max_length=100)),
                ('ph_num', models.CharField(max_length=15)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('resume', models.FileField(upload_to='resumes')),
                ('hear', models.CharField(max_length=100)),
                ('current_city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('available_date', models.DateField()),
                ('which_role', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
