# Generated by Django 3.2.6 on 2023-11-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_jobapplication_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
    ]
