# Generated by Django 3.2.6 on 2023-11-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='released_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.job'),
        ),
    ]
