# Generated by Django 3.2.6 on 2023-11-19 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_profile_released_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_meet_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_meet_link', models.URLField(blank=True, null=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.jobapplication')),
                ('scheduled_meet_attendees', models.ManyToManyField(blank=True, related_name='meeting_attendees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
