# Generated by Django 3.2.6 on 2023-11-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_meetingreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingReview',
        ),
    ]
