# Generated by Django 3.2.6 on 2023-11-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_meetingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('meeting_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.meetingschedule')),
            ],
        ),
    ]
