# Generated by Django 3.2.6 on 2023-11-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_meetingreview_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='decision',
            field=models.CharField(max_length=600),
        ),
    ]
