# Generated by Django 3.2.6 on 2023-11-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_meetingreview_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='meeting_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meetingschedule'),
        ),
    ]
