# Generated by Django 3.2.6 on 2023-11-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_decision_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='review',
        ),
        migrations.AddField(
            model_name='decision',
            name='applicant_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_review', to='main.meetingreview'),
        ),
    ]
