# Generated by Django 3.2.6 on 2023-11-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20231122_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='applicant_name',
            new_name='applicant',
        ),
    ]
