# Generated by Django 3.2.6 on 2023-11-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_decision_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_review', to='main.profile'),
        ),
    ]
