# Generated by Django 3.2.6 on 2023-11-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='log_type',
        ),
        migrations.AddField(
            model_name='logs',
            name='log_message',
            field=models.TextField(default='', max_length=200),
        ),
    ]
