# Generated by Django 3.2.6 on 2023-11-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_decision_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decision',
        ),
    ]
