# Generated by Django 3.2.6 on 2023-11-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='which_role',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
