# Generated by Django 3.2.6 on 2023-11-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20231123_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('meeting_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('forward_status', models.BooleanField(default=False)),
                ('accept_reject_status', models.BooleanField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobapplication')),
            ],
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
