# Generated by Django 3.2.6 on 2023-11-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20231123_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingschedule',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobapplication'),
        ),
    ]
