# Generated by Django 3.2.6 on 2023-11-23 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0047_auto_20231123_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decision',
            new_name='TeamLeadDecision',
        ),
    ]
