# Generated by Django 3.2.6 on 2023-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_rename_decision_teamleaddecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamleaddecision',
            name='log',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
