# Generated by Django 3.2.6 on 2023-11-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_teamleaddecision_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='team_lead_decision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='main.teamleaddecision'),
        ),
    ]
