# Generated by Django 3.2.6 on 2023-11-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_jobapplication_team_lead_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='team_lead_decision',
        ),
    ]
