# Generated by Django 3.2.6 on 2023-11-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_jobapplication_team_lead_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by_manager', models.BooleanField(default=False)),
            ],
        ),
    ]
