# Generated by Django 3.2.6 on 2023-11-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_managerdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdecision',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
