# Generated by Django 3.2.6 on 2023-11-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_managerdecision_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
