# Generated by Django 3.2.6 on 2023-11-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_jobapplication_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerdecision',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='teamleaddecision',
            name='log',
        ),
        migrations.AddField(
            model_name='managerdecision',
            name='log',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='managerdecision',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerdecision',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamleaddecision',
            name='logs',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
