# Generated by Django 3.2.6 on 2023-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20231124_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdecision',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managerdecision',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
