# Generated by Django 3.2.6 on 2023-11-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20231124_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdecision',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
