# Generated by Django 3.2.6 on 2023-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_managerdecision_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
