# Generated by Django 3.2.6 on 2023-11-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_emaillog_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
