# Generated by Django 3.2.6 on 2023-11-25 13:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_job_released_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='job_name', unique=True),
        ),
    ]
