# Generated by Django 3.2.6 on 2023-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20231129_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
