# Generated by Django 3.2.6 on 2023-11-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0069_jobapplication_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='is_accepted',
            new_name='hr_is_accepted',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='manager_is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='teamlead_is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetingschedule',
            name='scheduled_meet_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RejectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_rejection', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('logs', models.DateTimeField(auto_now_add=True, null=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobapplication')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
