# Generated by Django 3.2.6 on 2023-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20231130_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingschedule',
            name='scheduled_meet_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
