# Generated by Django 3.2.6 on 2023-12-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_remove_managerdecision_approved_by_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdecision',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobapplication'),
        ),
    ]
