# Generated by Django 3.2.6 on 2023-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_alter_emaillog_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
