# Generated by Django 3.2.6 on 2023-12-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_alter_emaillog_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jobapplication'),
        ),
    ]
