# Generated by Django 3.2.6 on 2023-12-14 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0082_managerdecision_scheduled_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerDecision',
            new_name='ManagerMainHrDecision',
        ),
    ]
