# Generated by Django 3.2.6 on 2023-12-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alllogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='logsjson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AllLogs',
        ),
    ]
