# Generated by Django 3.2.6 on 2023-12-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20231218_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='logs',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_view',
            field=models.BooleanField(default=False),
        ),
    ]
