# Generated by Django 3.2.6 on 2023-12-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20231221_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='logs',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
