# Generated by Django 3.2.6 on 2023-12-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20231223_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managermainhrdecision',
            name='reason',
        ),
    ]
