# Generated by Django 3.2.6 on 2023-12-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_remove_managermainhrdecision_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingschedule',
            name='scheduled_meet_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
