# Generated by Django 3.2.6 on 2023-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_alter_meetingschedule_scheduled_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingschedule',
            name='scheduled_meet_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
