# Generated by Django 3.2.6 on 2023-12-28 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0095_remove_profile_is_onboardinghr'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('snack_break_start', models.TimeField()),
                ('snack_break_end', models.TimeField()),
                ('lunch_break_start', models.TimeField()),
                ('lunch_break_end', models.TimeField()),
                ('holidays', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
