# Generated by Django 3.2.6 on 2023-12-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_usercalendarsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usercalendarsettings',
            name='holidays',
        ),
        migrations.AddField(
            model_name='usercalendarsettings',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='main.Holiday'),
        ),
    ]
