# Generated by Django 3.2.6 on 2023-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20231228_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercalendarsettings',
            name='holidays',
        ),
        migrations.AddField(
            model_name='usercalendarsettings',
            name='holidays',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
