# Generated by Django 3.2.6 on 2023-12-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='unique_url',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
